project:
  type: website
  output-dir: docs

website:
  title: "MedEdAI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: hospital
        href: https://www.directorsofclinicalskillseducation.org/

format:
  html:
    theme:
      - morph
    css: styles.css
    toc: true

editor: visual

date: today
