project:
  type: website
  output-dir: docs

website:
  title: "MedEdAI"
  favicon: images/MedEdAILogo2.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: mededref.qmd
        text: Articles
    right:
      - href: https://www.directorsofclinicalskillseducation.org/
        text: '<i class="bi bi-hospital"></i>'
        aria-label: "DOCS Website"

format:
  html:
    theme:
      - morph
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    css: styles.css
    toc: true

editor: visual

date: today
